dependencies:
- spyder 5.1.1
- cython
- matplotlib
- pandas
- pillow
- scikit-learn
- scipy
- sympy
# This is to avoid pulling an older IPython version
- ipython >=7.25
# For the workshop
- seaborn
- pyarrow

# This is required to avoid conda complaining about it.
- pip

# Required for jupyter-desktop-server
- websockify
- nbgitpuller
- pip:
    - jupyter-desktop-server
