dependencies:
- spyder
- cython
- matplotlib
- pandas
- pillow
- scikit-learn
- scipy
- sympy

# This is required to avoid conda complaining about it.
- pip

# Required for jupyter-desktop-server
- websockify
- nbgitpuller
- pip:
    - jupyter-desktop-server
