dependencies:
# TODO: Don't forget to remove the mainwindow.py patch in 4.2.1!
- spyder 4.2.0
- cython
- matplotlib
- pandas
- pillow
- scikit-learn
- scipy
- sympy
# This is to avoid pulling an older IPython version, which prints
# unnecessary warnings while using our debugger.
- ipython >=7.17

# This is required to avoid conda complaining about it.
- pip

# Required for jupyter-desktop-server
- websockify
- nbgitpuller
- pip:
    - jupyter-desktop-server
